server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: aflk.gateway
  cloud:
    gateway:
      routes:
        - id: aflk.auth # 구분하기 위한 id값으로 임의로 작성해도 무관
          predicates: # aflk.user/ 으로 요청이 들어오면
            - Path=/aflk.auth/**
          uri: lb://aflk.auth # 유레카 서버에서 aflk.auth를 찾아서 그곳으로 요청을 보낸다.
          filters:
            # url 재정의
            # ?<변수명>은 뒤에 나오는 정규식을 변수처럼 사용할 수 있도록 한다. ()는 하나의 묶음 처리 -> segment는 (.*)를 의미
            # 콤마(,)를 기준으로 왼쪽 url을 오른쪽 url로 재정의한다.
            # 콤마 기준 오른쪽 부분은 ${변수명}으로 url 가져오고 앞에 / 붙여준거라고 보면 된다.
            - RewritePath=/aflk.auth/(?<segment>.*), /$\{segment}

        # aflk.user/swagger 시작
        - id: aflk.user
          predicates:
            - Path=/aflk.user/swagger/**
          uri: lb://aflk.user
          filters:
            - RemoveRequestHeader=Cookie # 쿠키 삭제 후 실행
            - RewritePath=/aflk.user/(?<segment>.*), /$\{segment}
        - id: aflk.user
          predicates:
            - Path=/aflk.user/swagger-ui/**
          uri: lb://aflk.user
          filters:
            - RemoveRequestHeader=Cookie # 쿠키 삭제 후 실행
            - RewritePath=/aflk.user/(?<segment>.*), /$\{segment}
        - id: aflk.user
          predicates:
            - Path=/aflk.user/swagger-resources/**
          uri: lb://aflk.user
          filters:
            - RemoveRequestHeader=Cookie # 쿠키 삭제 후 실행
            - RewritePath=/aflk.user/(?<segment>.*), /$\{segment}
        - id: aflk.user
          predicates:
            - Path=/aflk.user/v2/**
          uri: lb://aflk.user
          filters:
            - RemoveRequestHeader=Cookie # 쿠키 삭제 후 실행
            - RewritePath=/aflk.user/(?<segment>.*), /$\{segment}
        # aflk.user/swagger 끝
        
        # aflk.user/signup --회원가입
        - id: aflk.user
          predicates:
            - Path=/aflk.user/user/signup
            - Method=POST
          uri: lb://aflk.user
          filters:
            - RemoveRequestHeader=Cookie # 쿠키 삭제 후 실행
            - RewritePath=/aflk.user/(?<segment>.*), /$\{segment}

        # aflk.user/signup --내 정보 보기
        - id: aflk.user
          predicates:
            - Path=/aflk.user/**
            - Method=GET
          uri: lb://aflk.user
          filters:
            - RemoveRequestHeader=Cookie # 쿠키 삭제 후 실행
            - RewritePath=/aflk.user/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter # JWT 검증을 위한 Custom GatewayFilter
