server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: aflk.gateway
  cloud:
    gateway:
      routes:
        - id: aflk.auth
          uri: lb://aflk.auth
          predicates:
            - Path=/aflk.auth/**
